// database.js - The central repository of baseline teams and players
const gameDatabase = {
    leagues: {
        "ENG 1 25/26": {
            name: "Premier League 25/26",
            teams: [
                {
                    id: "che",
                    name: "Chelsea FC",
                    budget: 120000000,
                    players: [
                        { name: "R. Sánchez", pos: "GK", rating: 81, img: "assets/robertsnchez.png" },
                        { name: "M. Gusto", pos: "RB", rating: 79, img: "assets/mgusto.png" },
                        { name: "W. Fofana", pos: "CB", rating: 79, img: "assets/wfofana.png" },
                        { name: "L. Colwill", pos: "CB", rating: 80, img: "assets/lcolwill.png" },
                        { name: "M. Cucurella", pos: "LB", rating: 85, img: "assets/marccucurella.png" },
                        { name: "R. James", pos: "RB", rating: 84, img: "assets/rjames.png" },
                        { name: "M. Caicedo", pos: "CDM", rating: 88, img: "assets/mcaicedo.png" },
                        { name: "C. Palmer", pos: "CAM", rating: 88, img: "assets/cpalmer.png" },
                        { name: "Pedro Neto", pos: "RM", rating: 82, img: "assets/pedroneto.png" },
                        { name: "E. Fernández", pos: "CM", rating: 85, img: "assets/efernndez.png" },
                        { name: "João Pedro", pos: "ST", rating: 82, img: "assets/joopedro.png" }                   ]
                },
                { id: "liv", name: "Liverpool FC", budget: 140000000, players: [
                        { name: "Alisson", pos: "GK", rating: 88, img: "assets/alisson.png" },
                        { name: "D. Szoboszlai", pos: "CAM", rating: 86, img: "assets/dszoboszlai.png" },
                        { name: "I. Konaté", pos: "CB", rating: 84, img: "assets/ikonat.png" },
                        { name: "V. van Dijk", pos: "CB", rating: 88, img: "assets/vvandijk.png" },
                        { name: "A. Robertson", pos: "LB", rating: 81, img: "assets/arobertson.png" },
                        { name: "R. Gravenberch", pos: "CDM", rating: 86, img: "assets/rgravenberch.png" },
                        { name: "A. Mac Allister", pos: "CM", rating: 85, img: "assets/amacallister.png" },
                        { name: "M. Salah", pos: "RM", rating: 89, img: "assets/msalah.png" },
                        { name: "C. Gakpo", pos: "LM", rating: 83, img: "assets/cgakpo.png" },
                        { name: "F. Wirtz", pos: "CAM", rating: 87, img: "assets/fwirtz.png" },
                        { name: "A. Isak", pos: "ST", rating: 87, img: "assets/aisak.png" }
                ] },
                { id: "ars", name: "Arsenal", budget: 130000000, players: [
                    { name: "D. Raya", pos: "GK", rating: 84, img: "assets/draya.png" },
                    { name: "J. Timber", pos: "RB", rating: 83, img: "assets/jtimber.png" },
                    { name: "W. Saliba", pos: "CB", rating: 88, img: "assets/wsaliba.png" },
                    { name: "Gabriel", pos: "CB", rating: 88, img: "assets/gabriel.png" },
                    { name: "R. Calafiori", pos: "LB", rating: 82, img: "assets/rcalafiori.png" },
                    { name: "M. Zubimendi", pos: "CDM", rating: 85, img: "assets/mzubimendi.png" },
                    { name: "D. Rice", pos: "CDM", rating: 87, img: "assets/drice.png" },
                    { name: "M. Ødegaard", pos: "CAM", rating: 87, img: "assets/mdegaard.png" },
                    { name: "B. Saka", pos: "RW", rating: 88, img: "assets/bsaka.png" },
                    { name: "V. Gyökeres", pos: "ST", rating: 87, img: "assets/vgykeres.png" },
                    { name: "G. Martinelli", pos: "LW", rating: 83, img: "assets/gmartinelli.png" }
                ] }, 
                { id: "mun", name: "Manchester United", budget: 110000000, players: [
                        { name: "S. Lammens", pos: "GK", rating: 81, img: "assets/slammens.png" },
                        { name: "Diogo Dalot", pos: "RB", rating: 78, img: "assets/diogodalot.png" },
                        { name: "H. Maguire", pos: "CB", rating: 81, img: "assets/hmaguire.png" },
                        { name: "A. Heaven", pos: "CB", rating: 74, img: "assets/aheaven.png" },
                        { name: "L. Shaw", pos: "LB", rating: 79, img: "assets/lshaw.png" },
                        { name: "Casemiro", pos: "CDM", rating: 82, img: "assets/casemiro.png" },
                        { name: "K. Mainoo", pos: "CDM", rating: 79, img: "assets/kmainoo.png" },
                        { name: "Amad", pos: "RW", rating: 80, img: "assets/amad.png" },
                        { name: "Matheus Cunha", pos: "ST", rating: 83, img: "assets/matheuscunha.png" },
                        { name: "Bruno Fernandes", pos: "CAM", rating: 88, img: "assets/brunofernandes.png" },
                        { name: "B. Mbeumo", pos: "RW", rating: 85, img: "assets/bmbeumo.png" }
                ] },
                {id: "mci", name: "Manchester City", budget: 200000000, players: [
                        { name: "G. Donnaruma", pos: "GK", rating: 88, img: "assets/gdonnaruma.png" },
                        { name: "N. O'Reilly", pos: "LB", rating: 84, img: "assets/noreilly.png" },
                        { name: "M. Guéhi", pos: "CB", rating: 85, img: "assets/mguhi.png" },
                        { name: "R.Dias", pos: "CB", rating: 86, img: "assets/rdias.png" },
                        { name: "M. Nunes", pos: "RB", rating: 82, img: "assets/mnunes.png" },
                        { name: "Rodri", pos: "CDM", rating: 89, img: "assets/rodri.png" },
                        { name: "B. Silva", pos: "CDM", rating: 85, img: "assets/bsilva.png" },
                        { name: "J. Doku", pos: "LW", rating: 83, img: "assets/jdoku.png" },
                        { name: "R. Cherki", pos: "CAM", rating: 85, img: "assets/rcherki.png" },
                        { name: "A. Semenyo", pos: "RW", rating: 84, img: "assets/asemenyo.png" },
                        { name: "E. Haaland", pos: "ST", rating: 91, img: "assets/ehaaland.png" }
                ]},
                {id: "tot", name: "Tottenham Hotspur", budget: 90000000, players: [
                        { name: "A. Kinský", pos: "GK", rating: 75, img: "assets/akinsk.png" },
                        { name: "D. Spence", pos: "LB", rating: 80, img: "assets/dspence.png" },
                        { name: "M. van de Ven", pos: "CB", rating: 84, img: "assets/mvandeven.png" },
                        { name: "C. Romero", pos: "CB", rating: 80, img: "assets/cromero.png" },
                        { name: "P. Porro", pos: "RB", rating: 80, img: "assets/pporro.png" },
                        { name: "R. Betancur", pos: "CDM", rating: 78, img: "assets/rbetancur.png" },
                        { name: "Palinha", pos: "CDM", rating: 80, img: "assets/palinha.png" },
                        { name: "M. Tel", pos: "LW", rating: 78, img: "assets/mtel.png" },
                        { name: "X. Simmons", pos: "CAM", rating: 83, img: "assets/xsimmons.png" },
                        { name: "R. Kolo Muani", pos: "RW", rating: 78, img: "assets/rkolomuani.png" },
                        { name: "D. Solanke", pos: "ST", rating: 79, img: "assets/dsolanke.png" },
                ]},
                {id: "new", name: "Newcastle United", budget: 95000000, players: [
                        { name: "A. Ramsdale", pos: "GK", rating: 78, img: "assets/aramsdale.png" },
                        { name: "L. Hall", pos: "LB", rating: 81, img: "assets/lhall.png" },
                        { name: "S. Botman", pos: "CB", rating: 81, img: "assets/sbotman.png" },
                        { name: "M. Thiaw", pos: "CB", rating: 82, img: "assets/mthiaw.png" },
                        { name: "T. Livramento", pos: "RB", rating: 81, img: "assets/tlivramento.png" },
                        { name: "S. Tonali", pos: "CDM", rating: 85, img: "assets/stonali.png" },
                        { name: "Joelinton", pos: "CM", rating: 81, img: "assets/joelinton.png" },
                        { name: "Bruno Guimarães", pos: "CM", rating: 86, img: "assets/brunoguimares.png" },
                        { name: "A. Gordon", pos: "LW", rating: 83, img: "assets/agordon.png" },
                        { name: "N. Woltemade", pos: "ST", rating: 81, img: "assets/nwoltemade.png" }
                ]},
                {id: "vil", name: "Aston Villa", budget: 85000000, players: [
                        { name: "E. Martínez", pos: "GK", rating: 84, img: "assets/emartnez.png" },
                        { name: "L. Digne", pos: "LB", rating: 80, img: "assets/ldigne.png" },
                        { name: "Pau Torres", pos: "CB", rating: 80, img: "assets/pautorres.png" },
                        { name: "E. Konsa", pos: "CB", rating: 84, img: "assets/ekonsa.png" },
                        { name: "M. Cash", pos: "RB", rating: 81, img: "assets/mcash.png" },
                        { name: "Y. Tielemans", pos: "CDM", rating: 85, img: "assets/ytielemans.png" },
                        { name: "A. Onana", pos: "CDM", rating: 81, img: "assets/aonana.png" },
                        { name: "E. Buendía", pos: "LW", rating: 81, img: "assets/ebuenda.png" },
                        { name: "M. Rogers", pos: "CAM", rating: 86, img: "assets/mrogers.png" },
                        { name: "J. McGinn", pos: "RW", rating: 81, img: "assets/jmcginn.png" },
                        { name: "O. Watkins", pos: "ST", rating: 83, img: "assets/owatkins.png" }                ]},
                {id: "bou", name: "AFC Bournemouth", budget: 75000000, players: []},
                {id: "ful", name: "Fulham FC", budget: 70000000, players: []},
                {id: "bre", name: "Brentford FC", budget: 65000000, players: []},
                {id: "whu", name: "West Ham United", budget: 60000000, players: [
                        { name: "M. Hermansen", pos: "GK", rating: 75, img: "assets/mhermansen.png" },
                        { name: "K. Walker-Peters", pos: "RB", rating: 76, img: "assets/kwalkerpeters.png" },
                        { name: "K. Mavropanos", pos: "CB", rating: 77, img: "assets/kmavropanos.png" },
                        { name: "A. Disasi", pos: "CB", rating: 77, img: "assets/adisasi.png" },
                        { name: "E. Diouf", pos: "LB", rating: 78, img: "assets/ediouf.png" },
                        { name: "J. Bowen", pos: "RM", rating: 83, img: "assets/jbowen.png" },
                        { name: "T. Souček", pos: "CDM", rating: 76, img: "assets/tsouek.png" },
                        { name: "Mateus Fernandes", pos: "CM", rating: 79, img: "assets/mateusfernandes.png" },
                        { name: "C. Summerville", pos: "LW", rating: 78, img: "assets/csummerville.png" },
                        { name: "T. Castellanos", pos: "ST", rating: 79, img: "assets/tcastellanos.png" },
                        { name: "Pablo", pos: "ST", rating: 73, img: "assets/pablo.png" },
                ]},
                {id: "bha", name: "Brighton & Hove Albion", budget: 55000000, players: []},
                {id: "sun", name: "Sunderland AFC", budget: 50000000, players: [
                        { name: "R. Roefs", pos: "GK", rating: 83, img: "assets/rroefs.png" },
                        { name: "Reinildo", pos: "LB", rating: 80, img: "assets/reinildo.png" },
                        { name: "O. Alderete", pos: "CB", rating: 80, img: "assets/oalderete.png" },
                        { name: "D. Ballard", pos: "CB", rating: 79, img: "assets/dballard.png" },
                        { name: "N. Mukiele", pos: "RB", rating: 82, img: "assets/nmukiele.png" },
                        { name: "N. Sadiki", pos: "CDM", rating: 78, img: "assets/nsadiki.png" },
                        { name: "G. Xhaka", pos: "CDM", rating: 85, img: "assets/gxhaka.png" },
                        { name: "C. Talbi", pos: "LW", rating: 78, img: "assets/ctalbi.png" },
                        { name: "E. Le Fée", pos: "CAM", rating: 78, img: "assets/elefe.png" },
                        { name: "T. Hume", pos: "RW", rating: 78, img: "assets/thume.png" },
                        { name: "B. Brobbey", pos: "ST", rating: 81, img: "assets/bbrobbey.png" }
                ]},
                {id: "lee", name: "Leeds United", budget: 45000000, players: []},
                {id: "not", name: "Nottingham Forest", budget: 40000000, players: []},
                {id: "eve", name: "Everton FC", budget: 35000000, players: []},
                {id: "crystal", name: "Crystal Palace", budget: 30000000, players: [
                        { name: "D. Henderson", pos: "GK", rating: 82, img: "assets/dhenderson.png" },
                        { name: "D. Muñoz", pos: "RB", rating: 82, img: "assets/dmuoz.png" },
                        { name: "C. Richards", pos: "CB", rating: 79, img: "assets/crichards.png" },
                        { name: "M. Lacroix", pos: "CB", rating: 81, img: "assets/mlacroix.png" },
                        { name: "J. Canvot", pos: "CB", rating: 74, img: "assets/jcanvot.png" },
                        { name: "T. Mitchell", pos: "LB", rating: 79, img: "assets/tmitchell.png" },
                        { name: "A. Wharton", pos: "CDM", rating: 81, img: "assets/awharton.png" },
                        { name: "W. Hughes", pos: "CDM", rating: 77, img: "assets/whughes.png" },
                        { name: "I. Sarr", pos: "RW", rating: 81, img: "assets/isarr.png" },
                        { name: "J. Strand Larsen", pos: "ST", rating: 77, img: "assets/jstrandlarsen.png" },
                        { name: "Yeremy Pino", pos: "LW", rating: 79, img: "assets/yeremypino.png" },
                ]},
                {id: "bur", name: "Burnley FC", budget: 25000000, players: []},
                {id: "wol", name: "Wolverhampton Wanderers", budget: 20000000, players: []},

            ]
        },
        "ESP 1 25/26": {
            name: "La Liga 25/26",
            teams: [
                { id: "bar", name: "FC Barcelona", budget: 100000000, players: [
                        { name: "Joan García", pos: "GK", rating: 86, img: "assets/joangarca.png" },
                        { name: "J. Koundé", pos: "RB", rating: 86, img: "assets/jkound.png" },
                        { name: "Pau Cubarsí", pos: "CB", rating: 83, img: "assets/paucubars.png" },
                        { name: "Eric García", pos: "CB", rating: 83, img: "assets/ericgarca.png" },
                        { name: "João Cancelo", pos: "RB", rating: 84, img: "assets/joocancelo.png" },
                        { name: "F. de Jong", pos: "CM", rating: 87, img: "assets/fdejong.png" },
                        { name: "Pedri", pos: "CM", rating: 90, img: "assets/pedri.png" },
                        { name: "Fermín", pos: "CAM", rating: 83, img: "assets/fermn.png" },
                        { name: "Lamine Yamal", pos: "RW", rating: 89, img: "assets/lamineyamal.png" },
                        { name: "Ferran Torres", pos: "ST", rating: 84, img: "assets/ferrantorres.png" },
                        { name: "Raphinha", pos: "LW", rating: 89, img: "assets/raphinha.png" }
                ] },
                { id: "atm", name: "Atlético Madrid", budget: 80000000, players: [
                        { name: "J. Oblak", pos: "GK", rating: 88, img: "assets/joblak.png" },
                        { name: "Marcos Llorente", pos: "RB", rating: 85, img: "assets/marcosllorente.png" },
                        { name: "Pubill", pos: "CB", rating: 80, img: "assets/pubill.png" },
                        { name: "D. Hancko", pos: "LB", rating: 83, img: "assets/dhancko.png" },
                        { name: "M. Ruggeri", pos: "LB", rating: 78, img: "assets/mruggeri.png" },
                        { name: "Giuliano", pos: "RM", rating: 82, img: "assets/giuliano.png" },
                        { name: "Pablo Barrios", pos: "CM", rating: 83, img: "assets/pablobarrios.png" },
                        { name: "Koke", pos: "CM", rating: 81, img: "assets/koke.png" },
                        { name: "A. Lookman", pos: "ST", rating: 83, img: "assets/alookman.png" },
                        { name: "A. Griezmann", pos: "ST", rating: 84, img: "assets/agriezmann.png" },
                        { name: "J. Alvarez", pos: "ST", rating: 86, img: "assets/jalvarez.png" }
                ] },
                {
                    id: "rmd",
                    name: "Real Madrid",
                    budget: 150000000,
                    players: [
                        { name: "T. Courtois", pos: "GK", rating: 90, potential: 90, age: 33, value: "€39M", wage: "€240K", img: "assets/courtois.png" },
                        { name: "T. Alexander-Arnold", pos: "RB", rating: 85, potential: 86, age: 26, value: "€58M", wage: "€230K", img: "assets/arnold.png" },
                        { name: "A. Rüdiger", pos: "CB", rating: 84, potential: 84, age: 32, value: "€27.5M", wage: "€220K", img: "assets/rudiger.png" },
                        { name: "D. Huijsen", pos: "CB", rating: 81, potential: 88, age: 20, value: "€47.5M", wage: "€120K", img: "assets/huijsen.png" },
                        { name: "Álvaro Carreras", pos: "LB", rating: 81, potential: 87, age: 22, value: "€38.5M", wage: "€140K", img: "assets/carreras.png" },
                        { name: "A. Tchouaméni", pos: "CDM", rating: 84, potential: 87, age: 25, value: "€50.5M", wage: "€200K", img: "assets/tchouameni.png" },
                        { name: "F. Valverde", pos: "CM", rating: 89, potential: 90, age: 26, value: "€120.5M", wage: "€340K", img: "assets/valverde.png" },
                        { name: "A. Güler", pos: "CM", rating: 83, potential: 89, age: 20, value: "€56.5M", wage: "€150K", img: "assets/guler.png" },
                        { name: "J. Bellingham", pos: "CAM", rating: 90, img: "assets/bellingham.png" },
                        { name: "K. Mbappé", pos: "ST", rating: 91, potential: 92, age: 26, value: "€157M", wage: "€610K", img: "assets/mbappe.png" },
                        { name: "Vini Jr.", pos: "ST", rating: 89, potential: 92, age: 24, value: "€141M", wage: "€320K", img: "assets/vinijr.png" }
                    ]
                },
                {id: "vil", name: "Villarreal CF", budget: 70000000, players: [
                        { name: "Luiz Júnior", pos: "GK", rating: 78, img: "assets/luizjnior.png" },
                        { name: "S. Mouriño", pos: "RB", rating: 78, img: "assets/smourio.png" },
                        { name: "Pau Navarro", pos: "CB", rating: 74, img: "assets/paunavarro.png" },
                        { name: "Renato Veiga", pos: "CB", rating: 78, img: "assets/renatoveiga.png" },
                        { name: "Pedraza", pos: "LB", rating: 76, img: "assets/pedraza.png" },
                        { name: "N. Pépé", pos: "RW", rating: 81, img: "assets/npp.png" },
                        { name: "Santi Comesaña", pos: "CM", rating: 79, img: "assets/santicomesaa.png" },
                        { name: "P. Gueye", pos: "CM", rating: 80, img: "assets/pgueye.png" },
                        { name: "Moleiro", pos: "LM", rating: 82, img: "assets/moleiro.png" },
                        { name: "Gerard Moreno", pos: "ST", rating: 81, img: "assets/gerardmoreno.png" },
                        { name: "G. Mikautadze", pos: "ST", rating: 79, img: "assets/gmikautadze.png" },
                ]},
                {id: "bet", name: "Real Betis", budget: 60000000, players: [
                        { name: "Álvaro Valles", pos: "GK", rating: 77, img: "assets/lvarovalles.png" },
                        { name: "Héctor Bellerín", pos: "RB", rating: 76, img: "assets/hctorbellern.png" },
                        { name: "Diego Llorente", pos: "CB", rating: 80, img: "assets/diegollorente.png" },
                        { name: "Natan", pos: "CB", rating: 78, img: "assets/natan.png" },
                        { name: "R. Rodríguez", pos: "LB", rating: 73, img: "assets/rrodrguez.png" },
                        { name: "Marc Roca", pos: "CDM", rating: 78, img: "assets/marcroca.png" },
                        { name: "Fornals", pos: "CM", rating: 81, img: "assets/fornals.png" },
                        { name: "S. Amrabat", pos: "CDM", rating: 79, img: "assets/samrabat.png" },
                        { name: "Antony", pos: "RW", rating: 81, img: "assets/antony.png" },
                        { name: "Cucho Hernández", pos: "ST", rating: 79, img: "assets/cuchohernndez.png" },
                        { name: "Abde", pos: "LW", rating: 80, img: "assets/abde.png" }
                ]},
                {id: "sev", name: "Sevilla FC", budget: 55000000, players: []},
                {id: "ath", name: "Athletic Bilbao", budget: 50000000, players: [
                        { name: "Unai Simón", pos: "GK", rating: 84, img: "assets/unaisimn.png" },
                        { name: "Gorosabel", pos: "RB", rating: 76, img: "assets/gorosabel.png" },
                        { name: "Vivian", pos: "CB", rating: 82, img: "assets/vivian.png" },
                        { name: "A. Laporte", pos: "CB", rating: 82, img: "assets/alaporte.png" },
                        { name: "Yuri Berchiche", pos: "LB", rating: 79, img: "assets/yuriberchiche.png" },
                        { name: "Ruiz de Galarreta", pos: "CDM", rating: 80, img: "assets/ruizdegalarreta.png" },
                        { name: "Jauregizar", pos: "CM", rating: 80, img: "assets/jauregizar.png" },
                        { name: "Iñaki Williams", pos: "RW", rating: 81, img: "assets/iakiwilliams.png" },
                        { name: "Nico Williams", pos: "LW", rating: 85, img: "assets/nicowilliams.png" },
                        { name: "Sancet", pos: "CAM", rating: 82, img: "assets/sancet.png" },
                        { name: "Guruzeta", pos: "ST", rating: 78, img: "assets/guruzeta.png" }
                ]},
                {id: "val", name: "Valencia CF", budget: 45000000, players: []},
                {id: "cel", name: "Celta Vigo", budget: 40000000, players: []},
                {id: "esp", name: "RCD Espanyol", budget: 35000000, players: []},
                {id: "alm", name: "Rayo Vallecano", budget: 30000000, players: [
                        { name: "A. Batalla", pos: "GK", rating: 79, img: "assets/abatalla.png" },
                        { name: "A. Rațiu", pos: "RB", rating: 80, img: "assets/araiu.png" },
                        { name: "F. Lejeune", pos: "CB", rating: 79, img: "assets/flejeune.png" },
                        { name: "N. Mendy", pos: "CB", rating: 75, img: "assets/nmendy.png" },
                        { name: "Pep Chavarría", pos: "LB", rating: 78, img: "assets/pepchavarra.png" },
                        { name: "P. Ciss", pos: "CDM", rating: 77, img: "assets/pciss.png" },
                        { name: "Unai López", pos: "CM", rating: 76, img: "assets/unailpez.png" },
                        { name: "I. Akhomach", pos: "RW", rating: 75, img: "assets/iakhomach.png" },
                        { name: "Álvaro García", pos: "LW", rating: 81, img: "assets/lvarogarca.png" },
                        { name: "Isi", pos: "CAM", rating: 80, img: "assets/isi.png" },
                        { name: "De Frutos", pos: "RW", rating: 81, img: "assets/defrutos.png" }
                ]},
                {id:"get", name: "Getafe CF", budget: 25000000, players: []},
                {id: "soc", name: "Real Sociedad", budget: 20000000, players: [
                        { name: "Álex Remiro", pos: "GK", rating: 82, img: "assets/lexremiro.png" },
                        { name: "J. Aramburu", pos: "RB", rating: 77, img: "assets/jaramburu.png" },
                        { name: "Jon Martín", pos: "CB", rating: 77, img: "assets/jonmartn.png" },
                        { name: "D. Ćaleta-Car", pos: "CB", rating: 74, img: "assets/daletacar.png" },
                        { name: "Sergio Gómez", pos: "LB", rating: 78, img: "assets/sergiogmez.png" },
                        { name: "Turrientes", pos: "CM", rating: 76, img: "assets/turrientes.png" },
                        { name: "Guedes", pos: "LW", rating: 78, img: "assets/guedes.png" },
                        { name: "Brais Méndez", pos: "CM", rating: 78, img: "assets/braismndez.png" },
                        { name: "Carlos Soler", pos: "CM", rating: 78, img: "assets/carlossoler.png" },
                        { name: "Barrenetxea", pos: "LW", rating: 78, img: "assets/barrenetxea.png" },
                        { name: "Oyarzabal", pos: "ST", rating: 83, img: "assets/oyarzabal.png" }
                ]},
                {id: "ala", name: "Alavés", budget: 10000000, players: []},
                {id: "elc", name: "Elche CF", budget: 5000000, players: []},
                {id: "lev", name: "Levante UD", budget: 2500000, players: []},
                {id: "osa", name: "CA Osasuna", budget: 1000000, players: []},
                {id: "mal", name: "RCD Mallorca", budget: 500000, players: []},
                {id: "gir", name: "Girona FC", budget: 250000, players: []},
                {id: "ovi", name: "Real Oviedo", budget: 100000, players: []}
            ]
        },

        "BL 25/26": {
            name: "Bundesliga 25/26",
            teams: [
                {id: "rbl", name: "RB Leipzig", budget: 100000000, players: [
                        { name: "M. Vandevoordt", pos: "GK", rating: 77, img: "assets/mvandevoordt.png" },
                        { name: "R. Baku", pos: "RB", rating: 79, img: "assets/rbaku.png" },
                        { name: "W. Orban", pos: "CB", rating: 83, img: "assets/worban.png" },
                        { name: "C. Lukeba", pos: "CB", rating: 83, img: "assets/clukeba.png" },
                        { name: "D. Raum", pos: "LB", rating: 83, img: "assets/draum.png" },
                        { name: "N. Seiwald", pos: "CDM", rating: 80, img: "assets/nseiwald.png" },
                        { name: "A. Ouédraogo", pos: "CM", rating: 74, img: "assets/aoudraogo.png" },
                        { name: "C. Baumgartner", pos: "CAM", rating: 81, img: "assets/cbaumgartner.png" },
                        { name: "Y. Diomande", pos: "RW", rating: 85, img: "assets/ydiomande.png" },
                        { name: "Rômulo", pos: "ST", rating: 78, img: "assets/rmulo.png" },
                        { name: "A. Nusa", pos: "LW", rating: 80, img: "assets/anusa.png" },
                ]},
            ]},

            "SA 25/26": {
                name: "Serie A 25/26",
                teams: [
                        {id:"int", name: "Inter Milan", budget: 120000000, players: [
                        { name: "Y. Sommer", pos: "GK", rating: 86, img: "assets/ysommer.png" },
                        { name: "D. Dumfries", pos: "RB", rating: 84, img: "assets/ddumfries.png" },
                        { name: "Y. Bisseck", pos: "CB", rating: 76, img: "assets/ybisseck.png" },
                        { name: "M. Akanji", pos: "CB", rating: 83, img: "assets/makanji.png" },
                        { name: "A. Bastoni", pos: "CB", rating: 87, img: "assets/abastoni.png" },
                        { name: "F. Dimarco", pos: "LB", rating: 86, img: "assets/fdimarco.png" },
                        { name: "P. Zieliński", pos: "CM", rating: 81, img: "assets/pzieliski.png" },
                        { name: "N. Barella", pos: "CM", rating: 88, img: "assets/nbarella.png" },
                        { name: "P. Sučić", pos: "CM", rating: 77, img: "assets/psui.png" },
                        { name: "M. Thuram", pos: "ST", rating: 85, img: "assets/mthuram.png" },
                        { name: "L. Martínez", pos: "ST", rating: 88, img: "assets/lmartnez.png" },]
                        },
                        {id: "juv", name: "Juventus FC", budget: 100000000, players: [
                        { name: "M. Di Gregorio", pos: "GK", rating: 81, img: "assets/mdigregorio.png" },
                        { name: "P. Kalulu", pos: "CB", rating: 80, img: "assets/pkalulu.png" },
                        { name: "Bremer", pos: "CB", rating: 86, img: "assets/bremer.png" },
                        { name: "L. Kelly", pos: "CB", rating: 78, img: "assets/lkelly.png" },
                        { name: "W. McKennie", pos: "CM", rating: 79, img: "assets/wmckennie.png" },
                        { name: "M. Locatelli", pos: "CDM", rating: 84, img: "assets/mlocatelli.png" },
                        { name: "K. Thuram", pos: "CM", rating: 81, img: "assets/kthuram.png" },
                        { name: "A. Cambiaso", pos: "LB", rating: 80, img: "assets/acambiaso.png" },
                        { name: "Francisco Conceição", pos: "CAM", rating: 79, img: "assets/franciscoconceio.png" },
                        { name: "K. Yıldız", pos: "CAM", rating: 82, img: "assets/kyldz.png" },
                        { name: "J. David", pos: "ST", rating: 81, img: "assets/jdavid.png" },
                        ]},
                {id: "acm", name: "AC Milan", budget: 90000000, players: [
                        { name: "M. Maignan", pos: "GK", rating: 87, img: "assets/mmaignan.png" },
                        { name: "A. Saelemaekers", pos: "RM", rating: 80, img: "assets/asaelemaekers.png" },
                        { name: "F. Tomori", pos: "CB", rating: 81, img: "assets/ftomori.png" },
                        { name: "M. Gabbia", pos: "CB", rating: 80, img: "assets/mgabbia.png" },
                        { name: "S. Pavlović", pos: "CB", rating: 77, img: "assets/spavlovi.png" },
                        { name: "D. Bartesaghi", pos: "LB", rating: 71, img: "assets/dbartesaghi.png" },
                        { name: "L. Modrić", pos: "CM", rating: 85, img: "assets/lmodri.png" },
                        { name: "Y. Fofana", pos: "CDM", rating: 81, img: "assets/yfofana.png" },
                        { name: "A. Rabiot", pos: "CM", rating: 85, img: "assets/arabiot.png" },
                        { name: "C. Nkunku", pos: "CAM", rating: 81, img: "assets/cnkunku.png" },
                        { name: "Rafael Leão", pos: "LW", rating: 84, img: "assets/rafaelleo.png" },
                        ]}
                ]},

        "WC 2026": {
            name: "World Cup 2026", teams: [
                {id:"fra", name: "France", budget: 100000000, players: [
                        { name: "M. Maignan", pos: "GK", rating: 85, img: "assets/mmaignan.png" },
                        { name: "T. Hernandez", pos: "LB", rating: 82, img: "assets/thernandez.png" },
                        { name: "D. Upamecano", pos: "CB", rating: 86, img: "assets/dupamecano.png" },
                        { name: "W. Saliba", pos: "CB", rating: 88, img: "assets/wsaliba.png" },
                        { name: "J. Koundé", pos: "RB", rating: 85, img: "assets/jkound.png" },
                        { name: "A. Tchouaméni", pos: "CDM", rating: 84, img: "assets/atchouamni.png" },
                        { name: "A. Rabiot", pos: "CM", rating: 84, img: "assets/arabiot.png" },
                        { name: "M. Olise", pos: "CAM", rating: 90, img: "assets/molise.png" },
                        { name: "D. Doué", pos: "LW", rating: 87, img: "assets/ddou.png" },
                        { name: "K. Mbappé", pos: "ST", rating: 91, img: "assets/kmbapp.png" },
                        { name: "O. Dembélé", pos: "RW", rating: 91, img: "assets/odembl.png" }
                ]},
                {id: "mex", name: "Mexico", budget: 80000000, players: [
                        { name: "R. Rangel", pos: "GK", rating: 78, img: "assets/rrangel.png" },
                        { name: "J Gallardo", pos: "LB", rating: 77, img: "assets/jgallardo.png" },
                        { name: "J. Vásquez", pos: "CB", rating: 80, img: "assets/jvsquez.png" },
                        { name: "E. Álvarez", pos: "CB", rating: 81, img: "assets/elvarez.png" },
                        { name: "I. Reyes", pos: "RB", rating: 78, img: "assets/ireyes.png" },
                        { name: "Fidalgo", pos: "CM", rating: 79, img: "assets/fidalgo.png" },
                        { name: "E. Lira", pos: "CM", rating: 81, img: "assets/elira.png" },
                        { name: "G. Mora", pos: "CAM", rating: 77, img: "assets/gmora.png" },
                        { name: "J. Quiñones", pos: "LW", rating: 83, img: "assets/jquiones.png" },
                        { name: "R. Jimenéz", pos: "ST", rating: 78, img: "assets/rjimenz.png" },
                        { name: "R. Alvarado", pos: "RW", rating: 79, img: "assets/ralvarado.png" }
                ]},
                {id:"bra", name: "Brazil", budget: 120000000, players: [
                        { name: "Alisson", pos: "GK", rating: 88, img: "assets/alisson.png" },
                        { name: "D. Santos", pos: "LB", rating: 76, img: "assets/dsantos.png" },
                        { name: "Gabriel", pos: "CB", rating: 87, img: "assets/gabriel.png" },
                        { name: "Marquinhos", pos: "CB", rating: 88, img: "assets/marquinhos.png" },
                        { name: "Danilo", pos: "RB", rating: 75, img: "assets/danilo.png" },
                        { name: "Casemiro", pos: "CDM", rating: 80, img: "assets/casemiro.png" },
                        { name: "Lucas Paquetá", pos: "CM", rating: 80, img: "assets/lucaspaquet.png" },
                        { name: "Bruno Guimarães", pos: "CM", rating: 85, img: "assets/brunoguimares.png" },
                        { name: "Vini Jr.", pos: "LW", rating: 91, img: "assets/vinijr.png" },
                        { name: "M. Cunha", pos: "ST", rating: 86, img: "assets/mcunha.png" },
                        { name: "Raphinha", pos: "RW", rating: 85, img: "assets/raphinha.png" }
                ]},
                {id:"spa", name: "Spain", budget: 110000000, players: [
                        { name: "Unai Simón", pos: "GK", rating: 85, img: "assets/unaisimn.png" },
                        { name: "M. Cucurella", pos: "LB", rating: 84, img: "assets/mcucurella.png" },
                        { name: "A. Laporte", pos: "CB", rating: 82, img: "assets/alaporte.png" },
                        { name: "P. Cubarsí", pos: "CB", rating: 85, img: "assets/pcubars.png" },
                        { name: "M. Llorente", pos: "RB", rating: 85, img: "assets/mllorente.png" },
                        { name: "Pedri", pos: "CM", rating: 88, img: "assets/pedri.png" },
                        { name: "Rodri", pos: "CDM", rating: 88, img: "assets/rodri.png" },
                        { name: "D. Olmo", pos: "CAM", rating: 84, img: "assets/dolmo.png" },
                        { name: "N. Williams Jr.", pos: "LW", rating: 82, img: "assets/nwilliamsjr.png" },
                        { name: "F. Torres", pos: "ST", rating: 80, img: "assets/ftorres.png" },
                        { name: "Lamine Yamal", pos: "RW", rating: 90, img: "assets/lamineyamal.png" }
                ]},
                {id: "eng", name: "England", budget: 90000000, players: [                        { name: "J. Pickford", pos: "GK", rating: 85, img: "assets/jpickford.png" },
                        { name: "N. O'Reilly", pos: "LB", rating: 84, img: "assets/noreilly.png" },
                        { name: "E. Konsa", pos: "CB", rating: 84, img: "assets/ekonsa.png" },
                        { name: "M. Guéhi", pos: "CB", rating: 85, img: "assets/mguhi.png" },
                        { name: "R. James", pos: "RB", rating: 84, img: "assets/rjames.png" },
                        { name: "E. Anderson", pos: "CDM", rating: 83, img: "assets/eanderson.png" },
                        { name: "D. Rice", pos: "CM", rating: 88, img: "assets/drice.png" },
                        { name: "J. Bellingham", pos: "CAM", rating: 91, img: "assets/jbellingham.png" },
                        { name: "M. Rashford", pos: "LW", rating: 85, img: "assets/mrashford.png" },
                        { name: "H. Kane", pos: "ST", rating: 90, img: "assets/hkane.png" },
                        { name: "B. Saka", pos: "RW", rating: 87, img: "assets/bsaka.png" }]},
                {id: "arg", name: "Argentina", budget: 95000000, players: [
                        { name: "E. Martínez", pos: "GK", rating: 85, img: "assets/emartnez.png" },
                        { name: "N. Molina", pos: "RB", rating: 77, img: "assets/nmolina.png" },
                        { name: "C. Romero", pos: "CB", rating: 82, img: "assets/cromero.png" },
                        { name: "L. Martínez", pos: "CB", rating: 81, img: "assets/lmartnez.png" },
                        { name: "F. Medina", pos: "CB", rating: 79, img: "assets/fmedina.png" },
                        { name: "R. De Paul", pos: "CM", rating: 83, img: "assets/rdepaul.png" },
                        { name: "A. Mac Allister", pos: "CM", rating: 85, img: "assets/amacallister.png" },
                        { name: "E. Fernández", pos: "CM", rating: 85, img: "assets/efernndez.png" },
                        { name: "T. ALWada", pos: "CAM", rating: 78, img: "assets/talwada.png" },
                        { name: "L. Messi", pos: "CAM", rating: 86, img: "assets/lmessi.png" },
                        { name: "L. Martínez", pos: "ST", rating: 88, img: "assets/lmartnez.png" }
                        ]},
                {id:"mor", name: "Morocco", budget: 85000000, players: [
                        { name: "Y. Bounou", pos: "GK", rating: 82, img: "assets/ybounou.png" },
                        { name: "A. Hakimi", pos: "RB", rating: 89, img: "assets/ahakimi.png" },
                        { name: "I. Diop", pos: "CB", rating: 76, img: "assets/idiop.png" },
                        { name: "C. Riad", pos: "CB", rating: 72, img: "assets/criad.png" },
                        { name: "N. Mazraoui", pos: "RB", rating: 80, img: "assets/nmazraoui.png" },
                        { name: "A. Bouaddi", pos: "CDM", rating: 78, img: "assets/abouaddi.png" },
                        { name: "N. El Aynaoui", pos: "CM", rating: 76, img: "assets/nelaynaoui.png" },
                        { name: "Brahim", pos: "RM", rating: 81, img: "assets/brahim.png" },
                        { name: "B. El Khannouss", pos: "CAM", rating: 78, img: "assets/belkhannouss.png" },
                        { name: "A. Ounahi", pos: "CM", rating: 79, img: "assets/aounahi.png" },
                        { name: "I. Saibari", pos: "CAM", rating: 80, img: "assets/isaibari.png" },
                ]},
        {id: "usa", name: "United States", budget: 75000000, players: [
                        { name: "M. Freese", pos: "GK", rating: 71, img: "assets/mfreese.png" },
                        { name: "S. Dest", pos: "RB", rating: 79, img: "assets/sdest.png" },
                        { name: "C. Richards", pos: "CB", rating: 79, img: "assets/crichards.png" },
                        { name: "T. Ream", pos: "CB", rating: 72, img: "assets/tream.png" },
                        { name: "A. Robinson", pos: "LB", rating: 81, img: "assets/arobinson.png" },
                        { name: "C. Pulisic", pos: "RW", rating: 85, img: "assets/cpulisic.png" },
                        { name: "W. McKennie", pos: "CM", rating: 79, img: "assets/wmckennie.png" },
                        { name: "T. Adams", pos: "CDM", rating: 79, img: "assets/tadams.png" },
                        { name: "T. Weah", pos: "RM", rating: 77, img: "assets/tweah.png" },
                        { name: "M. Tillman", pos: "CAM", rating: 79, img: "assets/mtillman.png" },
                        { name: "F. Balogun", pos: "ST", rating: 79, img: "assets/fbalogun.png" },
                ]},
        {id:"por", name: "Portugal", budget: 70000000, players: [                        { name: "Diogo Costa", pos: "GK", rating: 84, img: "assets/diogocosta.png" },
                        { name: "João Cancelo", pos: "RB", rating: 84, img: "assets/joocancelo.png" },
                        { name: "Tomás Araújo", pos: "CB", rating: 78, img: "assets/tomsarajo.png" },
                        { name: "Gonçalo Inácio", pos: "CB", rating: 81, img: "assets/gonaloincio.png" },
                        { name: "Nuno Mendes", pos: "LB", rating: 88, img: "assets/nunomendes.png" },
                        { name: "Vitinha", pos: "CM", rating: 90, img: "assets/vitinha.png" },
                        { name: "João Neves", pos: "CM", rating: 88, img: "assets/jooneves.png" },
                        { name: "Bruno Fernandes", pos: "CAM", rating: 88, img: "assets/brunofernandes.png" },
                        { name: "Bernardo Silva", pos: "CM", rating: 83, img: "assets/bernardosilva.png" },
                        { name: "Cristiano Ronaldo", pos: "ST", rating: 85, img: "assets/cristianoronaldo.png" },]}
            ]},
       
        "PT": {
            name: "Past Teams", teams: [
                { id: "atx22", name: "Austin FC 2022", budget: 100000000, players: [
                        { name: "B. Stuver", pos: "GK", rating: 75, img: "assets/bstuver.png" },
                        { name: "Z. Kolmanić", pos: "LB", rating: 68, img: "assets/zkolmani.png" },
                        { name: "J. Cascante", pos: "CB", rating: 70, img: "assets/jcascante.png" },
                        { name: "R. Gabrielsen", pos: "CB", rating: 74, img: "assets/rgabrielsen.png" },
                        { name: "J. Gallagher", pos: "RB", rating: 68, img: "assets/jgallagher.png" },
                        { name: "D. Pereira", pos: "CDM", rating: 67, img: "assets/dpereira.png" },
                        { name: "A. Ring", pos: "CDM", rating: 65, img: "assets/aring.png" },
                        { name: "S. Driussi", pos: "CAM", rating: 81, img: "assets/sdriussi.png" },
                        { name: "D. Fagundez", pos: "LW", rating: 74, img: "assets/dfagundez.png" },
                        { name: "M. Djittè", pos: "ST", rating: 76, img: "assets/mdjitt.png" },
                        { name: "E. Rigoni", pos: "RW", rating: 72, img: "assets/erigoni.png" }
                ] },
                {id: "rma-tp", name : "Real Madrid Three-Peat", budget: 150000000, players: [
                        { name: "K. Navas", pos: "GK", rating: 86, img: "assets/knavas.png" },
                        { name: "Marcelo", pos: "LB", rating: 87, img: "assets/marcelo.png" },
                        { name: "Sergio Ramos", pos: "CB", rating: 90, img: "assets/sergioramos.png" },
                        { name: "Pepe", pos: "CB", rating: 88, img: "assets/pepe.png" },
                        { name: "D. Carvajal", pos: "RB", rating: 85, img: "assets/dcarvajal.png" },
                        { name: "T. Kroos", pos: "CM", rating: 90, img: "assets/tkroos.png" },
                        { name: "L. Modrić", pos: "CM", rating: 90, img: "assets/lmodri.png" },
                        { name: "J. Rodríguez", pos: "CAM", rating: 88, img: "assets/jrodrguez.png" },
                        { name: "Cristiano Ronaldo", pos: "LW", rating: 94, img: "assets/cristianoronaldo.png" },
                        { name: "K. Benzema", pos: "ST", rating: 88, img: "assets/kbenzema.png" },
                        { name: "G. Bale", pos: "RW", rating: 90, img: "assets/gbale.png" }]
                },
                {id: "mci-treb", name: "Manchester City Treble Winners", budget: 200000000, players: [
                        { name: "Ederson", pos: "GK", rating: 88, img: "assets/ederson.png" },
                        { name: "M. Akanji", pos: "LB", rating: 85, img: "assets/makanji.png" },
                        { name: "Rúben Dias", pos: "CB", rating: 88, img: "assets/rbendias.png" },
                        { name: "J. Stones", pos: "CB", rating: 85, img: "assets/jstones.png" },
                        { name: "K. Walker", pos: "RB", rating: 84, img: "assets/kwalker.png" },
                        { name: "Rodri", pos: "CDM", rating: 90, img: "assets/rodri.png" },
                        { name: "İ. Gündoğan", pos: "CM", rating: 86, img: "assets/gndoan.png" },
                        { name: "K. De Bruyne", pos: "CM", rating: 92, img: "assets/kdebruyne.png" },
                        { name: "J. Grealish", pos: "LW", rating: 85, img: "assets/jgrealish.png" },
                        { name: "E. Haaland", pos: "ST", rating: 92, img: "assets/ehaaland.png" },
                        { name: "R. Mahrez", pos: "RW", rating: 87, img: "assets/rmahrez.png" },]

                },
                {id: "juv 18/19", name: "Juventus 2018/19", budget: 150000000, players: [
                        { name: "W. Szczęsny", pos: "GK", rating: 86, img: "assets/wszczsny.png" },
                        { name: "João Cancelo", pos: "RB", rating: 83, img: "assets/joocancelo.png" },
                        { name: "L. Bonucci", pos: "CB", rating: 86, img: "assets/lbonucci.png" },
                        { name: "G. Chiellini", pos: "CB", rating: 90, img: "assets/gchiellini.png" },
                        { name: "Alex Sandro", pos: "LB", rating: 86, img: "assets/alexsandro.png" },
                        { name: "M. Pjanić", pos: "CM", rating: 86, img: "assets/mpjani.png" },
                        { name: "E. Can", pos: "CM", rating: 80, img: "assets/ecan.png" },
                        { name: "B. Matuidi", pos: "CDM", rating: 85, img: "assets/bmatuidi.png" },
                        { name: "P. Dybala", pos: "CAM", rating: 89, img: "assets/pdybala.png" },
                        { name: "M. Mandžukić", pos: "ST", rating: 85, img: "assets/mmanduki.png" },
                        { name: "Cristiano Ronaldo", pos: "ST", rating: 94, img: "assets/cristianoronaldo.png" },
                ]},
                {id: "fra22", name: "France 2022 World Cup", budget: 100000000, players: [
                        { name: "H. Lloris", pos: "GK", rating: 87, img: "assets/hlloris.png" },
                        { name: "J. Koundé", pos: "CB", rating: 83, img: "assets/jkound.png" },
                        { name: "R. Varane", pos: "CB", rating: 85, img: "assets/rvarane.png" },
                        { name: "L. Hernández", pos: "CB", rating: 84, img: "assets/lhernndez.png" },
                        { name: "N. Kanté", pos: "CDM", rating: 90, img: "assets/nkant.png" },
                        { name: "P. Pogba", pos: "CM", rating: 86, img: "assets/ppogba.png" },
                        { name: "K. Coman", pos: "LW", rating: 85, img: "assets/kcoman.png" },
                        { name: "T. Hernández", pos: "LB", rating: 84, img: "assets/thernndez.png" },
                        { name: "A. Griezmann", pos: "ST", rating: 85, img: "assets/agriezmann.png" },
                        { name: "O. Giroud", pos: "ST", rating: 81, img: "assets/ogiroud.png" },
                        { name: "K. Mbappé", pos: "ST", rating: 91, img: "assets/kmbapp.png" },
                ]}
            ]
        },
        "MISC": {
            name: "Miscellaneous", teams: [
                { id: "BLXI", name: "Bluelock XI", budget: 100000000, players: [
                        { name: "Gagamaru", pos: "GK", rating: 85, img: "assets/gagamaru.png" },
                        { name: "Hyoma Chigiri", pos: "LB", rating: 84, img: "assets/hyomachigiri.png" },
                        { name: "Ikki Niko", pos: "CB", rating: 87, img: "assets/ikkiniko.png" },
                        { name: "Aryu Jyubei", pos: "CB", rating: 86, img: "assets/aryujyubei.png" },
                        { name: "Meguru Bachira", pos: "RB", rating: 88, img: "assets/megurubachira.png" },
                        { name: "Karasu Tabito", pos: "CDM", rating: 88, img: "assets/karasutabito.png" },
                        { name: "Yoichi Isagi", pos: "CAM", rating: 90, img: "assets/yoichiisagi.png" },
                        { name: "Nagi", pos: "CAM", rating: 93, img: "assets/nagi.png" },
                        { name: "Yukimiya Kenyu", pos: "LW", rating: 89, img: "assets/yukimiyakenyu.png" },
                        { name: "Shoei Barou", pos: "ST", rating: 90, img: "assets/shoeibarou.png" },
                        { name: "Rin Itoshi", pos: "RW", rating: 94, img: "assets/rinitoshi.png" }]}
                ]

    }
}
};